### ISSUE TITLE
how can one tell if a trade is executed ?

### ISSUE THREAD

**Issue by dlefcoe** [coinfloor/python-library#2]
How can one tell if there is a trade executed please ?

it appears from the code that the methods are:

                "Authenticate",
        data["method"] = "GetBalances"
        data["method"] = "GetOrders"
        data["method"] = "EstimateMarketOrder"
        data["method"] = "PlaceOrder"
        data["method"] = "CancelOrder"
        data["method"] = "CancelAllOrders"
        data["method"] = "GetTradeVolume"
        data["method"] = "WatchOrders"
        data["method"] = "WatchTicker"

### is there a method to:

1. get the details of the last trade
2. watch for trade executed

**Comment by timfoxell** [comment]
The API's are documented here: https://github.com/coinfloor/API

Have a read through the WatchOrders and WatchTicker methods as I think these are what you are after.
https://github.com/coinfloor/API/blob/master/WEBSOCKET-README.md#watchorders
https://github.com/coinfloor/API/blob/master/WEBSOCKET-README.md#watchticker

**Comment by dlefcoe** [comment]
There allow the user to see the orders on the order book, but not the specific orders placed by the user.

How can one do this please?

**Comment by timfoxell** [comment]
Please see the OrdersMatched notice. Authenticated users receive notice of their own orders. Users that have subscribed to the orders feed of an order book receive notice of all orders in that book.

https://github.com/coinfloor/API/blob/master/WEBSOCKET-README.md#ordersmatched

**Comment by dlefcoe** [comment]
Agreed, i see this.

Okay, the issue is that the lient needs to be `authenticated` prior to invoking `WatchOrders` method otherwise the user can only see general market orders.

Thank you.

**Comment by timfoxell** [comment]
A user will always get OrdersMatched notices for their own orders. Even if they are not watching the orders of a specific book.
The message flow section at the very top of the Websocket documentation includes this information. https://github.com/coinfloor/API/blob/master/WEBSOCKET-README.md
